route:
  receiver: telegram
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 5m

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: "8601261719:AAGOVcB3vMGwGPnK4c3bERxgTAYbWWTdqf8" 
        chat_id: 338396081
        parse_mode: HTML
        send_resolved: true
        message: |
          🚨 <b>{{ .CommonLabels.alertname }}</b>
        
          <b>Status:</b> {{ .Status }}
          <b>Severity:</b> {{ .CommonLabels.severity }}
        
          <b>Summary:</b>
          {{ .CommonAnnotations.summary }}
        
          <b>Job:</b> {{ .CommonLabels.job }}
          <b>Instance:</b> {{ .CommonLabels.instance }}
