server {
    listen 80;
    server_name www.4mc0pa.realhost-free.net;

    # фронт
    location / {
        root /var/www/frontend;
        try_files $uri /index.html;
    }

    # backend статика
    location /backend/ {
        alias /var/www/backend/;
    }

    # PHP
    location ~ ^/backend/(.+\.php)$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/backend/$1;
    }
}
